version: '3'
services:
  email_queue:
    build: .
    image: bishoyromany/email:0.0.1
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_ENCRYPTION: TLS
      KAFKA_QUEUE:
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISMS: PLAIN
      GROUP_ID:
    command: 'php artisan queue:work'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
