version: '3.9'
services:
  email_queue:
    build: .
    volumes:
      - .:/app
    command: 'php artisan queue:work'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
